# This workflow is triggered when a pull request is closed on the 'production' branch. If the pull request was merged, it will build the release APK and publish it as a GitHub Release. The workflow also handles version bumping and tagging using the 'mathieudutour/github-tag-action' action.
name: Android Release

on:
  push:
    branches:
      - production

permissions:
  contents: write

jobs:
  build-release:
    name: Build and Publish APK
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      KEYSTORE_FILE: release.keystore
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump Version and Push Tag
        id: versioning
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Release Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > "$KEYSTORE_FILE"
      - name: Gradle Script Permission
        run: |
          chmod +x gradlew
      - name: Build Release
        run: |
          ./gradlew assembleRelease
      - name: Verify APK Exists
        run: |
          ls -lah app/build/outputs/apk/release/
      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.versioning.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          files: |
            app/build/outputs/apk/release/*.apk
          generate_release_notes: true
